version: '3'

services:
  poll:
    build: poll/
    ports:
      - 5000:80
    depends_on:
      - redis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - poll-tier
    restart: on-failure
  redis:
    image: redis
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - poll-tier
      - back-tier
  worker:
    build: worker/
    depends_on:
      - redis
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - back-tier
    restart: on-failure
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - result-tier
      - back-tier
    restart: on-failure
  result:
    build: result/
    ports:
      - 5001:80
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - result-tier
    restart: on-failure

networks:
  poll-tier:
    driver: bridge
  result-tier:
    driver: bridge
  back-tier:
    driver: bridge

volumes:
  db-data:
